import Data.Char

numPairs :: Int -> Int -> String -> Int
numPairs total _ "" = total
numPairs total numKnights (x:xs)
    | isUpper x = numPairs total (numKnights + 1) xs
    | isLower x = numPairs (total + numKnights) numKnights xs
    | otherwise = error "panic"

numPairsOfLetter :: Char -> String -> Int
numPairsOfLetter x xs = numPairs 0 0 filtered
    where filtered = filter (\c -> c == toUpper x || c == toLower x) xs

numPossiblePairs :: String -> Int
numPossiblePairs xs =
    numPairsOfLetter 'a' xs + numPairsOfLetter 'b' xs + numPairsOfLetter 'c' xs

slice :: Int -> Int -> String -> String
slice i j s = drop i (take j s)

countCaps :: Char -> String -> Int
countCaps c str = length as where as = [x | x <- str, x == toUpper c]

solve3 :: Int -> Int -> String -> Int
solve3 distance repeats str = let
    wrapped = str ++ str ++ str
    l = length str
    stringAround i = slice (l+i-distance) (l+i+distance+1) wrapped
    countAround i x
        | isLower (x!!i) = countCaps (x!!i) (stringAround i)
        | otherwise = 0
    in
        (repeats-2) * sum (map (\i -> countAround i str) [0..l-1])
        + checkHead distance str
        + checkTail distance str

checkHead :: Int -> String -> Int
checkHead distance str = let
    wrapped = str ++ str
    l = length str
    stringAround i = slice (i-distance) (i+distance+1) wrapped
    countAround i x
        | isLower (x!!i) = countCaps (x!!i) (stringAround i)
        | otherwise = 0
    in
        sum (map (\i -> countAround i str) [0..l-1])

checkTail :: Int -> String -> Int
checkTail distance str = let
    wrapped = str ++ str
    l = length str
    stringAround i = slice (l+i-distance) (l+i+distance+1) wrapped
    countAround i x
        | isLower (x!!i) = countCaps (x!!i) (stringAround i)
        | otherwise = 0
    in
        sum (map (\i -> countAround i str) [0..l-1])

---- UGLEEEEEE but idc, I'm going to bed

main :: IO ()
main = do
    let data1 = "ABCCcaaCAAAbccbCAcbAaCBCaAaBCacAbAaccCcAcBcBBbCBcAaCacabaBbAcBbaccaBbCCAAbcAbbBcCbcCAcBBbAaABAcAabcc"
    print $ numPairsOfLetter 'a' data1

    let data2 = "ABCaaCBCAAabbBbBAaCacaaACBCaBaACCCaBBBaBBcCbBCaaCaBCBacBacacAaBACaCbcBcCBcaBbCBCABBAbCbBAaBBBAaCAACcbBABcABbbaBbcAbBaccBbCCabAbABAaBAbbbcACcbbcaacAaAbcCbcBcBbcBaacAAbCBAcbBABAabBBAbAaaBaCbaAACBaaBAcbabCBCBcaaCCCbCbacCccAbAccbBccABCbaCAbAAbbcBcBaBAaAaCAcAAcBBAcccaBAbBBCbcBBcAAAbbaACbaBACCBABaaBcaBbBC"
    print $ numPossiblePairs data2

    let data3 = "CacaBBBAAaabBBaAaAaAcBCaCaAABbaacCaaCaCAabaAbBbBABcaaaAaCaCcacCcCcbAbABABcBcacbaccCaBcaABaBaACcCcAbCBBcACaccCBbBCCaCBbAbbCcABcaBaAAAcbbBAACCabCCbCACBbBbcCaAbaAcCabACcabAaaCaBCcABAaCcAAabBCCcACAcbCCAcCcaAcBBbaCccbbBaBCcAbBaaCBbBBabBcCcBCBbcCAcAABaABaABBBAcACbBaaaCaBBcaAbbcbabCbBaccCBbBBaacBbCCBABbBBAbAbabcbAcBCaCBcCBaCabbBbBbbACCccAcABcbbcBacaCcabAcbcaCACabBBAABcaaCbCBacCaABBAbBaCBcbBcAbCAACAbbcCbaBAbcbcAccCbAababAAAbbbcbbBaCCCBaAACBCbaBbcbcCBcBAbCCcbABBbABaaccABABacCcBCabcAaAaBCbBCCAcbbBbbccbBBCcCCcBabaACACBBcccaacCaCBcCACCabCcBacBaCcCbaaabaBBaaACaACacBaCabbCcAaBBcccACCBAbBcbCcBAbaAbcCccCBaBbbBCCCaAbABBbacAaAcCcbbBBcCabaCbcAbAAcAbAbCaCAAabcACACBABBcCAbcaBBBBbaBacbaBbaabaaCBAAbcbBBBCBcBAACABcBbCCbAbAaCcCabaCACBcAaCCCcbBbAAaAAbaCaAAcCbaACcBbaBcaBBaAAccBABccbBbCbABAaCAAcaBabbBBCACabAcCAbBaaBbbcBCAacBbCACccaCABbBaaBCaCBcBACbCBbbCbAccCBACcBCcbCccAcaaCbACabcABaABAaCCACACCCAabCBAbCcAAbbAbAAcAcbcAAACbbAaCABBCaACCCBcAAAbABBcbCBCAcBBBBcbBbACcAACBaCbAaAcBAaBabbbBbAAcBBCcAaBbCcAaBbABCBBAAacBaBcBBAccBCcAaBcCCCbAABcABbcaACBaCcCaCACCbbCbBbACBabCBCBcCbcbCbBBbaaCBCBAcCACbAACBbaBbaBAaBCCcbCbCcCcBabABABbBCbbcBcABaAABbbcBCAbcAaBAccAbAbabAcccacCbBaACcbbbAABccacbAAAAaCbbacacaABABcAAAAaAaBbbAbBaaCABBbBbcCabcCbAAbBACBBbCbbAacbcCCAaBbaaaabbCBCCaaaABBACCcbbbCBBBAbbacbbACcbCabABbCabcabbcCcBabABBacAaaAAaAbcabcAaccabbBBAabccAbcbBBbBCAAbaAaCAcAccBcaACacbbcaaCabCccbbBccbbAbcaBAaCbaBACCBCabaAbabbbBcCBaABbabbABaCBCcCcACaCBaAcaBBaaaBbBCBacabBBcBbccBCcBACcbCaaaBACcAbababCCbaaAAcBbabbCBbaCaBABabAbaAbCAbBAaaccbACAabBBccabBccbBabCAaAbCCaaBaBabaaBacCBaABbAAAcbAcCabBababcaCBcabBcccAAAAbAAaBCCCCAabAaAbBBcbAcaBbCaAACCcbaCaAcaACcaabbCaBBbBACccbAacCacCabCccbbbbCccCAAACAbBbBBABBBabbCbcCbCbBAcBcCBBCaaBBbaabABaBccaCBbCcACBBCAbbbbccbcCcAccBAbCbaAcaCAcBabCbaAbCABBAbaCcBaCAaCcACAAccbAABcbAcCaabAbbaCcBccABAbccBBCCaBaccCaacCacabCBabAcbBCCcBBAbcBBBACCbcccCbacBcbcBaaBcCCCCCaCBCBCcbBccabACBBBaCCcbCBbCBbabacBbaABbbABcAbabaBBCCCcaacBbAabbBcbbcacCbbbccBaBAaCCAcBCBCaaCCCabBAAAAbabcAbACABcBCbcCcCbbacacAbBBBBccCBBCBcbBaabACCAacaCBCacbAbCCcABBACbACCbAABbCCCcAAbBabAbAccBCcCcABBcaaCCBCaBbaBAAacCBCCBcaCaBAACaCbAaBCCACCcACaaAAbCBbbbACAbCCAacCAbBAAABAAAccacBABbBcCAAcbBabAccbBcAACbBBacabcACCCacCbBAaAaaCBcacCCAbbcBCBbBbBABbBbCCCaCbbCCAACBABbaaccAAcbAaaAcaBaBcBAcCcBbbCaCcbacACBCAaBcbBbbBaccCCaCbaCAabBBbcBCabAACaBbaCCBAaabACaaCbcCaccCCCaBbbcCBAbABcAbAbbaCBBbcBCBabbcaccCccCAcbAcccAbBcAccbcbBBBBccBCbBCcCaAABCCAAaACBcBCcbCAaabaCaacCaBbABaABCCABbcACbaAaCaBCcBaCaBcbbAaBAaBAcCcbcaCbBACcbCBABBaBACcaccBBBcCBBbcbCcAcacABCbaBCCbCbBBCaaAaCaBbcCAABCBbCaababCCbccBBcacAccAbcBbaaBcabABAACCbaAAAaacbbBBCBaAcacCbcCcBbcaCbCCcaCBaBAaacbBBcAABcbbbcCCcacaBabbcCCACCBbBAccbAbaAaAcccAAcCBBbaaaCBaaaCBCaBABAbABAAbAAcAACBacBACCBBbaCccbaaBcbCcbbCAAaCBBBccBAaaCBCAbbBaabAbAcaaABcabcCbAAaBaccbccacbAaBaAAcabBAcBaAcABabbAaCAbBabaAbcCBbccCCbcbAcbaaAbbCAccBbcBbCbAcBccBabcBCaCaccCbaacaAbbBcBaCbaCaBcCcBBBaBACbcBcaBcacAaCccbACBabBAcAaaAcAacbbaCBBAccbCacaaCccBBaacaCBbCAcbCaCabbACaBCAbCaBcCAbCBAacacABCaACabAabcAACcBcCCbBaAaaccCacCaCcCaACccbCbBcBACBABcbBcabCCbAAaAAbaCCaaccCABACAaCABbCbbCBCaCAbbaCBAabaBbBBcCBaabbCCABCAbAcCcaCcaacBaAcaBaBbACBcABBAccbAccaAbacaacBBCcbcBBbcBCBaAbCaAbbCAaABaaAbAabcbaCbAacacBbbCAABcaCcaCaAbbbacACababaCaAcbccabAcbCaBAAabbACcaCCCBBBAcACBbbAAcCCAAbcCbcaCABAABBBaCBaABAbABabACAbCCcbbCCbaBabBCBACBccbACCbaCcCcaBABaCbccbACCBbCbcbcbbBBbCaaaBCcaABBAccAaBbBAabBBaCCaCbCaAABaACcBBaaCCaabBbACACABbaCaabAABaAbACbaccCccccbBaABcBAbCBAAAABbcCABbcAccBaBAcbcACaacBBaCaBcaBbAcAAAbABCBcBCcCcacCabcCabccABbAcaCbAAaabbCaaCbcaBcaacbabbCCaCbACcabABccaCbBcaACbAabBaAbAcCbcaCAACcACBAAaCCAccBccAAABcaBBBAbaaCcCAacbCcAcbCbCCBCCBCbaccAabBbAabcAcbCBabBCcBAbCBbCCacBaACABbBaacCcbAAABAcBbbAbCBCAcaaCAcBacBcCcABcABCCbccbaBBabcbccBCcAbaAaCCCCcbBaccAbcAAaAbbBabBAccACbaCAaCCBbaacabBbbCaACcaBBACaaCBACaCAAbcacBABcaacCBbabABabCAABabAcAacCCCcaaCBbBACcaabcCbbCBAbbAbAABBbACacAAaBacABabCAbCcCAcabBbcaACacCbaaccBcbCaabaaABBbAbAaACababCcBCbBAabBCcACBCCBAbcbccCACccaCACBAcABcacaAcCCCacACcaAbBcABBACCBCaCcbCAbCbcACBbabaCBbBabaabCCcbACaAbcAabCAabaaaaBcAACccbBbbbaCAbCBBaAbcCaCacBAbAaBbCbCaCaCaABaAaaCacbBaAAaBCccBBAbBbAbbccAaBacAcBCBCBCcabCBBCACaAcacbccBAbBbBaAabBCCBabACBaCcCAAbACAccBbCCbCbbBbaaBBcBacCacbcACCaAaaaaAAAcCBBccbcCaACaCcCACCCABAcBBcAccAbAaBaBBccBCaACbACacAccBbaAbAaAAaAaaBaacbAabBBBAccBcccbBacBBCCcCCCaabBBaaACcACCAaacabcBcbccCCccBcaAaacBbCABBbaBaCAcABccaBbBCBaBCcAbAcABCcbcbCBbBCbcbAAabacaBCaCABBCbACbcCAbcCbCAaAaACaacCCBcbccAcabcAabCccBcCBBBbaAcBcBCBcBbABCCbbbbBACBCBacCcbCBbbCBAcAaaBbBcCbacAacCcACabaaCCbBAcaCbcacBBacBCCACAABCccaAaBcABAcABcCaCCabccBcacBaaAAAAaCcaCCbABBCACAbCAccacbBbbbccBcbaACaabBccBabBCCBACBaACbacCccCbbcBbCcbBccCaAbCBBabACAAaBAabaABCaccbaabcccabaAcCAbcacaCAcCCBBaCbbCaCacAcaACAcbCaAAbCbcabcBcBCaAAbCaABaabbaacAcbaaaacaAbCBBCCacbacCAaAbBCccaBaBbbbcBCBaBAAACBacACAcaCbcAaabBBbBBcBBAaBbabcACBcBBcACcBccCaBCcBBCBcaAAaCcaABAbacBAabccBcABaAbCBACccCCcbAaBCAACABcBbcbacCaCCaACbACBBbBaaAcBABCCaAcaCBCCbbaCbacaccbBaaacbABaBaaccBaBcacCAABCbcBcAbACbAcBBcAbacBABCabaBaBacBbCaCccAbBbaaaBBbcaCACAACCcaCcaAbbcaAAacbABAAbcCccbAAaBBBbbcacAbaAAabCcACAbAcAbbBBcbBbAcBcCaACaabaCCbccbbBaABBcbBbaBaAAabbBaBabccBAAAacCcbaBAcbCBcCABacaaCBaBAccbCaCCbaABBCcCAAbbabcaaAaCCcBBababACACabbABCAaCBABbbAAAbbBCACABABabacAbcbBBCbbBCaCbcBACCcBccAACacaaacBcccbbaBAbacCbCBCaAaabcbAcbcccBabbAbcBaaCACCcBcbAabaacCabbaBAbcaBbCaBbAcCACBAABaCcABBBbaccbbcCBbaBcbABbBBBcbBbbcACBbbCbcbbccBcBbCbCcBAcAcaaCbcAAbCbaCaaABbcacCbbcAbAcCaabCacaaacBACcbCacbcACAcBCbabbcaAcaaCaaccABcaAbcCaBCCAaCcAABCaBabacbaACcBaBAbBAABacccBaBAAAAbccAccABaBABAbACcacCcbAabaaACAABAbAAacbBcCAccbaAaAaCbBCaAABBBCAbACcaCaCcAcbaCcaACACABCccbbAcbBCAbaAAcAAbcAbbabBAbbBbbBCbccAbaBcbCCCBBaaacAcCABaaaBcAbBbABcBbBABAbccAabbaaCcAaaAbaBaaBBaBBabaBBccCCbBBACcBabaCCABBBBCBacABCABABAaBcBbbCCcaCbbcAcAacAcBCBCcCbAAABAbCccBaaAbcCbAcbbBccCCBAcBBAcCabCABbAAccbcbbaaAaaabBCaBbcCbcbacCbCcbBaAAaabCbCCAcabbbaCCcaacacaBabBacCacbCccCbbBcbbAaCabcccbABAAcCbCABCbbBBAAaAcBbCCaCBABaaabbcCCBCbBaCaCbcCAcAacCBBBaCCCacBbccABacacBccaBcaaCCbcbaBBBAcAccaCBaAbBACCAcAaCCCCABBABcCAbaAaCCccaAbBCcabbcBbbACcBBBAACcAaCaCbbCCCAcaBAbaBACCBBabAaBbbCbBcACcabCAaaBbbbbcCcAaaCABCAAcBABCCCcBCAACBaBaAbccBCBacaBAabcCcbBAaacacBbbCaBbBbacCBccbAbBbBbbBCCABbCCBACBBACBcABAcAACaCaCabacabbBaAbABCBaBCCCCBCacCaCCAABacCaBabcaaccBbbaCCCAcaABBCbbbacBBBAcCcAbBcbAaBcaBaAbcAacAcbcbCBACbbAbbCAaCcbBaBAAaCcCBaAaAABAabbBbcAcbbbAABbAaAAcbcacacCcbbCaAACccbABAbCbCBcabaCabbCbAbbcCcACbAbAAcABbbccCCAbbBBcCCBaacCCACaABBCbBacCbBcCCbACAACcbCACacCcBBCcBbAcAbCBCACacBbBBcBbcAccabABCACBbCbCbcaBCBbcaACabBcAaABcABbbBaCCCcacccbBACcBaCaBACBAABCaababAcAaCBCbCCbBaaaaBBAbAacbaacbCcABCBAbACaCbABaAbcBBcbaCaccccAaAacAaaBaaabCcccACbAcCAaBCAcbabAaCcbAAbcBbacBcBAbBCaAbCCcAcbAcBBbAACACbBacCbBcabbcacCacbCACbCcBcbcCCCabaBbCcCAABcBaccacbacABbbcaCBbACbbBBcccBaBCCCCCaCBBabABaBBcbABBBbAAbcCaAcCBBaCCaBBcBAAAbaAacBBCaabbAbcbBCcCccaBCaCabaAcCBaaBBCAcCbbBAbababACaaCBaAaaAAcaBbabCccAaccCCBBccaAcAacACCBaAaaaCCcbAaaAcCabcABBbaAbCBCcCbABCcCCaabcABCBbCbaAbcbCABcaCBaCaacCBCbAbCAbBbBcBcBACbcbbBaCABbABBcBbcaCBaacBCbBABbcBcbcbCAbccAcBcacCcCaCbCCcACbAbcbCCaaBCaCbBCbCbbcbCaBbBCbbCbAaCaCcCBcaCcbBbccbccabaCACcCBABACCBCbAAbcCBBbbBCAbacBCBcACCBbCCBAAcaABAbCbAAaacBacaBCabcCBaCcACCbccAcCBACbaBaBcCACbacaCaBcccaCAAcCBACCACBbBacaBBAAACcaAACcACbAAbAaCABbCBCbbcCbBaCCbBccBBbBCaaABCcAbacBaBcCbaaAAcbcBcCbABAaCbABaaBbABcCCbcbBBcBBaAaaACAaaaBbBbbCbCccBabAcbBAABaacbaCbaaabCcaAbaBaCCBabCABBCbcbCaAcBccbcCbaBbbABCCbCBacaBCbCaBABBABCAbbbAbbBacbaacBCbcBAacbAacaccbCbCaaAcBcCAbACbbAaBCBaaAabbccCacBbBAaaCbccBBBaAbbCcAcBacACcBABbbBAbcACBaCcABCbBacAcBCCaBAacaBBcBcbAbaCaBAaAabCaBACaabCCbbCABAbABcbccBaBbACAbBCBCCABcccccCaCcAaaCBBBABbCCBaAcbbaccaabaBcCcbBAcBbCbCBcaabaabbacccCaBabCbbABBcbCbABaCbBCacbbACcBcCbAAaBaCAcAbbCAbaabbabbBCAabbCAacBaBbbACCAbAcaBCCccCCbcbacBAccCAbbcACabBBBbBAABbBBBcCBCcAAaBaAaBAaBabaBacCBaaACAbCaAACBCCaabBAAacAABaCcbcBAacaaAaACcBCbBaBCbBcBcCBBccccbCBAacAabCcCcACabBCAabCaBcAbccCBBAbbBBAcACabABacbacaabcbBaBacAAcBaBcbcacCBaBCAcBCcbBacccAAAAAaaccaCAAcaAaBcabcCACCaAbABccaabBCccAcBbBAcACBcCbaaBabbaBBCABAbabAcbCBcCcBCbcccccAAbACbcCcBbacaaACbcaBaAbBCAaCABaBbbAabbbBCacbbCBBaABaBabBCbaABcCCacBCAcCBCcCBABaAcabccbbaAaABbcbBBCbABCACbbAaBbaaACBcCCbCaCBCAaBAbCAbAaacaBCccbCBBbACCbbAACBABbCaabaACAcAcACcBaCBCCacBACCcbAcaCACcaCBBbaBAbBcBcaAaABbcbaAbaccBbaBbcBacbCCcABaBCbbcbaBCcbCacAbcAABbAAaCBCCaaBBaABCABAaCbccCccCAabCbbccbBbbCcbcccBcaabaBcCaAaCcCACCacbaAAbCCAAabcbBcAabCcaaCacBCbbCAcCCBCBbccaacBbccAbAcaBbccAbCACaaaaAABcCcaBBCaACAcbaAAabacBACCcbaccBACBCAbbABbaBBAAcBcBACcBCACcaabcaAaBaAbbCBABaAaABAbcCCBCCBbCbBbaabbAAaaBAcbACBacAccbacBaAccCbCCAABCCcbcccCAAcabABCAbaBccbcCCbBAbaAcCcACCBAbabBBcBbBBBCbccCccBBAAbbBCCaACCABaBaCCAaaCcCacbAaaaaCaBcBbBCbcBCbCCBccbbcBaBcABBCCbBBAcbcCBAABAbABbcAcCaBAcAbCAAAcbbaBbcBbBabBacAAabbcBaBBBcbcCCAaccACbCBBccacaAaCAAaCaBAacAACbBCcbcbCabBcccabaaBCAABBBccCabCbcaCaBbccBACBaaACcBCbcaCAAbBabAAAaCACCBBccBcCcAaBAbcaCaBBaaAaAcAaBBCaABBCbCbaaAaCCcAaCCACCCacAabccBbABBCbABbaaAccCcBbCabAbbcCcbCacccBcCcCBcABCAAAabCCcaCAbcCbbbbCAbbCaCCCCaCcAcCaBcbCbCACaBCbcccabcBbcAbAbbBABCaBBaacabAACACaaCCcBBbCCaCaBBAACccbBaBBABAbaaCAbaCBABAcaCbCAcacBaCacccBaacccabAABbcAccBaaBCAcbAcCBCcbCAAAAcBBAcBcBaACbbaaBABaacAAaCacCABbBCbbBcBABCAAACcBcCCbCAcAaAaAcBbCaABcBccCCccBabbABbbCcCCbBBbBCbAaaaACaAaCbAccCABCaaCBBbbcabAccbCBBCaACBCAABBbBBcabbAbbBbcCbCAbaacbACBaCAABbaacaABCaaAbabcBCcAACACcCbBCCaBAACAABcbAACABBAaccaBCcaaAACCbAcBbbbBaAbBBbBCacbCcbBCbcCCccccaCBcbCBcACCcacCaaCBAbaaacCaababAacbcbACBBAabccbcbCCbAcbcccaabbcbCbcbACBAbbCABccCCCcbCbBBBBaccccCcBcCBacabAAABCBaAabBBBBbbAbBcbaBBBbaABbcCCBcBcabCbccBcBbAbaBcCaccBAaCBacABacCcCBBCCbabBcBCbacbaaabBAccbBaBacaCBbbBacBaCBCacbcBccaAABbCAacBbAcaCbBaCAAcacAaBCaBabacaaAcbaCcaaABBBCCBcCCCBBCBCBBbAAaAbAcccBbaccbcABcCCBcbBAaBABcAbBCCcCbcbaacCbbaAAABBBacccBbaCBCaabccabAaAbacCBCbbBccabCBCAcBcbBBbCCbaBAcBABaCBaaBCcBacbBCaaCcbACaccaBcCbCAcCBbCbBaCBCaACBAcABBcAbAAacCaBCbacAACACbBCCccABCbbBccacBAAaAAbABCcCBbCaacAbbbCaBAbcbcbBCBcCabbcAcbaAcCBcCaccCcBBcbbaCCabCBaacCaAcAAccCACcbCAAcbAaBACabAAbbaCcCbaBCBbcCcBCaBAbcAcBbAcCCACBBaBbCBBCcbcccBCBaaaCcBAacCAcbcaCCCABCCBaCbCbcbcaCaABaCbAcBBbbcAbabBCbACCCAcbaCaBCbccbbbcbBcccbAAcccacAcCbAAccAACcaBBBAbbCCBbAB"
    let sample3 = "AABCBABCABCabcabcABCCBAACBCa"
    print $ solve3 1000 1000 data3
